version: '2'

services:      
  mongo:
      container_name: mongo
      image: mongo:latest
      ports:
          - 27018:27018
      # environment:
      #     - MONGO_DATA_DIR=/data/db
      #     - MONGO_LOG_DIR=/dev/null
      volumes:
          - ./data/mongo:/data/db    


